version: "3.8"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: patuvashti
    container_name: patuvashti-app
    restart: unless-stopped
    tty: true
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - patuvashti

  db:
    image: postgres:12-alpine
    restart: unless-stopped
    container_name: patuvashti-db
    tty: true
    ports:
    - "5432:5432"
    volumes:
    - ./psql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: patuvashti_dev
      POSTGRES_DB: patuvashti
      POSTGRES_PASSWORD: ASecretPassword
    networks:
      - patuvashti

  nginx:
    image: nginx:stable-alpine
    container_name: patuvashti-nginx
    ports:
    - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db
    networks:
      - patuvashti


networks:
  patuvashti:
    driver: bridge

