version: "3.8"

networks:
  patuvashti:
    driver: bridge

services:
  app:
    build:
      context: ./
      dockerfile: php.dockerfile
    image: patuvashti
    container_name: patuvashti-app
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - patuvashti

  db:
    image: postgres:12-alpine
    restart: unless-stopped
    container_name: patuvashti-db
    tty: true
    ports:
    - "5432:5432"
    volumes:
    - ./psql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: patuvashti_dev
      POSTGRES_DB: patuvashti
      POSTGRES_PASSWORD: ASecretPassword
    networks:
      - patuvashti

  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: patuvashti-nginx
    ports:
    - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - app
      - db
    networks:
      - patuvashti

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    container_name: composer
    volumes:
    - ./src:/var/www/html
    depends_on:
      - app
    user: laravel
    networks:
      - patuvashti
    entrypoint: ["composer"]

  npm:
    image: node:12-alpine
    container_name: npm
    volumes:
    - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: artisan
    volumes:
    - ./src:/var/www/html
    depends_on:
      - db
    user: laravel
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - patuvashti

  laravel:
    build:
      context: .
      dockerfile: laravel.dockerfile
    container_name: laravel
    volumes:
      - ./src:/var/www/html
    user: laravel
    entrypoint: ["/tmp/vendor/laravel/installer/bin/laravel"]
    networks:
      - patuvashti
