version: "3.8"

networks:
  laravel_docker:
    driver: bridge

services:
  app:
    build:
      context: ./
      dockerfile: php.dockerfile
    container_name: laravel-docker-app
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel_docker

  db:
    image: postgres:12-alpine
    restart: unless-stopped
    container_name: laravel-docker-db
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - ./psql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: laravel_docker
      POSTGRES_PASSWORD:
    networks:
      - laravel_docker

  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - app
      - db
    networks:
      - laravel_docker

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    container_name: composer
    volumes:
      - ./src:/var/www/html
    depends_on:
      - app
    user: laravel
    networks:
      - laravel_docker
    entrypoint: ["composer"]

  npm:
    image: node:12-alpine
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]
    networks:
      - laravel_docker
    ports:
      - "3000:3000"
      - "3001:3001"

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    user: laravel
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - laravel_docker

  laravel:
    build:
      context: .
      dockerfile: laravel.dockerfile
    container_name: laravel
    volumes:
      - ./src:/var/www/html
    user: laravel
    entrypoint: ["/tmp/vendor/laravel/installer/bin/laravel"]
    networks:
      - laravel_docker
